### ISSUE TITLE
Value for VideoNetHost and VideoNetPort

### ISSUE THREAD

**Issue by sunghoon031** [JuanTarrio/rebvo#5]
I am getting the following error:

``````
MTrack: Error enviando paquete de 257737 bytes a 10.73.32.54:2708! 11: Resource temporarily unavailable
``````

I think this is because I did not provide the correct value for VideoNetHost and VideoNetPort. 

Here are my questions:
(1) What are these parameters? Why do I need them?
(2) If I set `VideoNetEnabled=0` in GlobalConfig file, then I can run the program, but it does not do anything after showing the line "Loaded 2965 File names". What is the issue here?

Can you tell me how I can fix this issue, please?

**Comment by JuanTarrio** [comment]
You need to provide your own ip address or 127.0.0.1:2708 if running standalone in order for the results to ve transmitted by network.

In order to see them you need to run the visualizer.
best

**Comment by sunghoon031** [comment]
Thank you ! Changing VideoNetHost in GlobalConfig to 127.0.0.1 made it work :)
So awesome !!
