### ISSUE TITLE
How well does inertial-aided REBVO perform with EuRoC MAV dataset?

### ISSUE THREAD

**Issue by sunghoon031** [JuanTarrio/rebvo#6]
I am very interested in the inertial-aided version, and I would like to test it with EuRoC MAV dataset.

Have you ever tried this with EuRoC MAV dataset? If so, how well did it perform?

**Comment by JuanTarrio** [comment]
I'm uploading videos on my youtube channel of the inertial aided version of REBVO running on the EuRoC for a recent submition we have made. 
The code will be available upon acceptance.

**Comment by sunghoon031** [comment]
Very Cool! Thank you for your reply. I have sent you an email to request an access to the source code.

**Comment by edgar-explorer** [comment]
@sunghoon031  have you got the code?
